name: decorated_icon
description: An icon that supports shadow decorations.
version: 1.0.0
repository: https://github.com/benPesso/flutter_decorated_icon

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
